apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      name: grafna-port
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_image
        imagePullPolicy: Never
        ports:
          - containerPort: 3000