apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: kek
  name: php-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 5000
      name: php-port
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: php_image
        imagePullPolicy: Never
        ports:
          - containerPort: 5000