apiVersion: v1
kind: Service
metadata:
  name: influx-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app: influx
#  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pv-claim
  labels:
    app: influx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: influx-deploy
  labels:
    app: influx
spec:
  selector:
    matchLabels:
      app: influx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influx
    spec:
      containers:
        - image: influx_image
          name: influx-container
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
              name: influx-port
          volumeMounts:
            - name: influx-pv-volume
              mountPath: /var/lib/influxdb
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: influx-pv-volume
          persistentVolumeClaim:
            claimName: influx-pv-claim
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock